name = "America"
code = "AMER"
slug = "america"
flag = "🌎"
region = "North America"
population = 992823193
land_area_km2 = 40099122
currency_code = "AMER"
currency_name = "El Dorado"
money_supply_b_usd = 29909
token_price_usd = 0
visa_free_destinations = 0
visa_free_inbound = 0
oceans = ""
