name = "Arctic"
code = "ARCO"
flag = "❄️"
region = "Oceans"
population = 0
land_area_km2 = 15558000
currency_code = "ARCO"
currency_name = "Arctic Credit"
money_supply_b_usd = 0
token_price_usd = 0
visa_free_destinations = 0
visa_free_inbound = 0
