name = "Asia"
code = "ASIA"
flag = "🏮"
region = "Asia"
population = 3701065962
land_area_km2 = 18806258
currency_code = "ASIA"
currency_name = "Silk Road"
money_supply_b_usd = 52742
token_price_usd = 0
visa_free_destinations = 0
visa_free_inbound = 0
oceans = ""
