name = "Atlantic"
code = "ATL"
flag = "🌀"
region = "Oceans"
oceans = ""
population = 2563555950
land_area_km2 = 85133000
currency_code = "ATL"
currency_name = "Atlantic Credit"
money_supply_b_usd = 56284
token_price_usd = 0
visa_free_destinations = 0
visa_free_inbound = 0
