name = "Bir Tawil"
code = "BTWL"
slug = "bir-tawil"
flag = "🏜️"
region = "Terra Nullius"
oceans = ""
population = 0
land_area_km2 = 2060
currency_code = "BTWL"
currency_name = "Terra Nullius"
money_supply_b_usd = 0
token_price_usd = 0
visa_free_destinations = 0
visa_free_inbound = 0
