name = "Eurasia"
code = "EURA"
slug = "eurasia"
flag = "🦣"
region = "Eurasia"
population = 4834047975
land_area_km2 = 52010690
currency_code = "EURA"
currency_name = "Silk Road"
money_supply_b_usd = 77366
token_price_usd = 0
visa_free_destinations = 0
visa_free_inbound = 0
oceans = ""
