name = "Indian Ocean"
code = "IND"
flag = "🐚"
region = "Oceans"
population = 0
land_area_km2 = 70560000
currency_code = "IND"
currency_name = "Indian Credit"
money_supply_b_usd = 0
token_price_usd = 0
visa_free_destinations = 0
visa_free_inbound = 0
