name = "Ixion"
code = "IXIO"
slug = "ixion"
flag = "🎡"
region = "Solar System"
oceans = ""
population = 0
land_area_km2 = 1582000
currency_code = "IXIO"
currency_name = "Perpetual"
money_supply_b_usd = 0.000
money_supply_b_usd_prev = 0.000
token_price_usd = 0.000000
token_price_usd_prev = 0.000000
visa_free_destinations = 0
visa_free_inbound = 0
