name = "Juno"
code = "JUNO"
slug = "juno"
flag = "💍"
region = "Solar System"
oceans = ""
population = 0
land_area_km2 = 203000
currency_code = "JUNO"
currency_name = "Moneta"
money_supply_b_usd = 0
token_price_usd = 0
visa_free_destinations = 0
visa_free_inbound = 0
