name = "Quaoar"
code = "QUAO"
slug = "quaoar"
flag = "🪶"
region = "Solar System"
oceans = ""
population = 0
land_area_km2 = 3730000
currency_code = "QUAO"
currency_name = "First Song"
money_supply_b_usd = 0.000
token_price_usd = 0.000000
visa_free_destinations = 0
visa_free_inbound = 0
