name = "Southern"
code = "SOUO"
flag = "🧊"
region = "Oceans"
oceans = ""
population = 4400
land_area_km2 = 21960000
currency_code = "SOUO"
currency_name = "Southern Credit"
money_supply_b_usd = 0
token_price_usd = 0
visa_free_destinations = 0
visa_free_inbound = 0
