name = "Umbriel"
code = "UMBR"
slug = "umbriel"
flag = "🌑"
region = "Solar System"
oceans = ""
population = 0
land_area_km2 = 4296000
currency_code = "UMBR"
currency_name = "Eclipse"
money_supply_b_usd = 0.000
token_price_usd = 0.000000
visa_free_destinations = 0
visa_free_inbound = 0
